name: Build and Deploy Spring Boot
on:
 push:
   branches: [ "main" ]
jobs:
 build-and-deploy:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
   
   steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'

     - name: Create .env file
       run: |
         cat << EOF > .env
         DEBUG_ENABLED=${{ vars.DEBUG_ENABLED }}
         LOG_LEVEL=${{ vars.LOG_LEVEL }}
         COOKIE_DOMAIN=${{ vars.COOKIE_DOMAIN }}
         NEXT_MONGO_DB_URL=${{ secrets.NEXT_MONGO_DB_URL }}
         NEXT_MONGO_DB_USER=${{ secrets.NEXT_MONGO_DB_USER }}
         NEXT_MONGO_DB_PASS=${{ secrets.NEXT_MONGO_DB_PASS }}
         JWT_COOKIE_SECRET=${{ secrets.JWT_COOKIE_SECRET }}
         EOF

     - name: Build with Gradle
       run: ./gradlew build

     - name: Login to GitHub Container Registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3

     - name: Lowercase the repo name
       run: |
         echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

     - name: Build and push Docker image
       uses: docker/build-push-action@v5
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ghcr.io/${{ env.REPO_LOWER }}:latest
         cache-from: type=gha
         cache-to: type=gha,mode=max

     - name: Deploy to remote server
       run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
         chmod 600 ~/.ssh/deploy_key
         ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts
         
         ssh -i ~/.ssh/deploy_key -l charliepank ${{ secrets.VM_IP }} -vv '
           # Pull image
           docker pull ghcr.io/${{ env.REPO_LOWER }}:latest
           
           # Stop and remove existing container
           docker stop spring-users || true
           docker rm spring-users || true
           
           # Start new container
           docker run -d \
             --name spring-users \
             --network webnet \
             --restart unless-stopped \
             -e NEXT_MONGO_DB_URL="${{ secrets.NEXT_MONGO_DB_URL }}" \
             -e NEXT_MONGO_DB_USER="${{ secrets.NEXT_MONGO_DB_USER }}" \
             -e NEXT_MONGO_DB_PASS="${{ secrets.NEXT_MONGO_DB_PASS }}" \
             ghcr.io/${{ env.REPO_LOWER }}:latest
         '
